;----------------------------------------------------------------------------------------------------------------------
; file:	windows.inc
; assembler:	masm 64 bit assembler
; last update:	1998-04-23 - created
;	2013-02-18 - make 64 bit
;----------------------------------------------------------------------------------------------------------------------

WIN64	equ	1		; some win64 defines

	include	windef.inc
	include	wtypes.inc
	include	winerror.inc
	include	winbase.inc
	include	winnt.inc
	include	winuser.inc
	include	wingdi.inc

